### ISSUE TITLE
Add optional param to specify scripting directory

### ISSUE THREAD

**Issue by leojonathanoh** [startersclan/Compile-SourceScript#1]
## Feature
cmdlet should accept an optional param to specify the `scripting` directory.

## Current behavior

Compiling an `.sp` or `.sma` file outside the `sourcemod` or `amxmod` `scripting` directory fails with error about not being able to find the compiler.

## Suggested behavior

Compiling an `.sp` or `.sma` file outside the `sourcemod` or `amxmod` `scripting` directory should be able to find the compiler, based on an optional param to specify the `scripting` directory.

Edit: It appears that this optional param will not be supported for `amxmodx` on Windows, since its `compile.exe` expects `.sma` to be found in the `scripting` directory.

**Comment by joeltimothyoh** [comment]
See https://github.com/startersclan/Compile-SourceScript/pull/2 for reason for closure.

Closing.

**Comment by leojonathanoh** [comment]
it is a good idea, but the fact that this will not work on Windows as described in #1 OP, means the param won't work across all environments. So i guess this cannot be implemented.

However, if this tool was used strictly for `sourcemod` only, the developer will be able to source control the plugin source code  e.g. `/path/to/repo/myplugin.sp` outside of the compiler location  e.g. `/path/to/sourcemod/spcomp`. Compiling would then be possible using:

```
Compile-SourceScript -File /path/to/repo/myplugin.sp -ScriptingDirectory /path/to/sourcemod
```

perhaps it might be reopened in future, but not many use `sourcemod` anymore.
