### ISSUE TITLE
Module does not provide an exit code when compiler compile fails

### ISSUE THREAD

**Issue by leojonathanoh** [startersclan/Compile-SourceScript#6]
## Bug

cmdlet does not exit with non-zero exit code when compiler compile fails.

## Expectation

cmdlet does exit with non-zero exit code when compiler compile fails.

Two ways to get a non-zero exit code in powershell:

1. `throw` a terminating error in the script (we lose the exit code of the compiler)
2. `exit 1` in the script (we exit the entire powershell process)
3. Populate the `$global:LASTEXITCODE` for consumer to read.

Edit: I think its better to pass exit code via option 3 instead of the first two options.

**Comment by joeltimothyoh** [comment]
Would like to know what kind of compile failure you are referring to. Pertaining to this project or the actual compilation of plugins? Also, since this module serves as an all-in-one wrapper, it would probably make more sense to return its own exit code(s). The use of `throw` is definitely preferable to `exit 1` as it would be consistent with error handling behavior in PowerShell.

**Comment by leojonathanoh** [comment]
Updated issue

**Comment by leojonathanoh** [comment]
integration false positives in #2 is because the module is not handling compiler compilation fail cases correctly. 

2 errors to handle:
- Wrapper-specific errors (not directly compiler-related) should be handled as normal in powershell.
- Compiler produces an exit code and that should be available to a consumer. Note that `amxxpc` always exits with `0` even when compilation fails.

**Comment by joeltimothyoh** [comment]
> integration false positives in #2 is because the module is not handling compiler compilation fail cases correctly.

Which CI jobs have shown false positives? By false positive you mean a false error or false pass?

> Wrapper-specific errors (not directly compiler-related) should be handled as normal in powershell.

The use of `throw` and `Write-Error` takes care of that.

> Compiler produces an exit code and that should be available to a consumer. Note that amxxpc always exits with 0 even when compilation fails.

It's exactly such inconsistencies that I'm rather unwilling to handle compiler specific errors. Perhaps supported could be added to output the compiler's exit code on each run. Moreover, if the compiler wrapper is used, multiple plugins end up getting compiled within the same run and in so makes the exit code misrepresentative of the run.

**Comment by leojonathanoh** [comment]
> Which CI jobs have shown false positives? By false positive you mean a false error or false pass?

false passes. Check out the green ticks jobs, where the integration tests did not consider failed test cases as having failed.

> The use of throw and Write-Error takes care of that.

Yes. There can be a little improvements, but this is not directly related to the present issue.

> It's exactly such inconsistencies that I'm rather unwilling to handle compiler specific errors. Perhaps supported could be added to output the compiler's exit code on each run. Moreover, if the compiler wrapper is used, multiple plugins end up getting compiled within the same run and in so makes the exit code misrepresentative of the run.

I've added a a branch that handles compiler specific errors, and enhances integration tests to also read `$global:LASTEXITCODE` so that it can properly handle `amxxpc` errors. Also I added fail integration test cases so ensure the module properly populates the `$global:LASTEXITCODE`. I'll open a pr
