### ISSUE TITLE
Obscure error message when compilers fail due to missing dependencies

### ISSUE THREAD

**Issue by leojonathanoh** [startersclan/Compile-SourceScript#8]
## Current

Obscure error message when compilers fail due to missing dependencies

## Expectation

Unobscure error message when compilers fail due to missing dependencies

## Discussion

E.g. 

```sh
$ pwsh -Command 'Compile-SourceScript -File /path/to/my-repo/scripting/foo.sma -SkipWrapper -Force -Verbose'
WARNING: The names of some imported commands from the module 'Compile-SourceScript' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Starting Compile-SourceScript
Compiler: '/path/to/my-repo/scripting/amxxpc'
Compiling...
Compiling foo.sma...
End of Compile-SourceScript.
Compile-SourceScript : No such file or directory
At line:1 char:110
+ ... cript.psm1; Compile-SourceScript -File /path/to/my-repo/scripting/foo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], Win32Exception
+ FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Compile-SourceScript
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

# Run compiler directly 
$ /path/to/my-repo/scripting/amxxpc
bash: /path/to/my-repo/scripting/amxxpc: No such file or directory

# Or 
$ /path/to/my-repo/scripting/amxxpc
compiler failed to instantiate: amxxpc32.so: cannot open shared object file: No such file or directory
```

Perhaps it should be documented that user might need to install compiler dependencies: https://github.com/startersclan/Compile-SourceScript/tree/v2.1.0/test/scripts/dep/linux

@joeltimothyoh

**Comment by joeltimothyoh** [comment]
The error message thrown by `Compile-SourceScript` is `No such file or directory` and matches the message by the compiler itself when executed directly instead. I don't necessarily see how the message is obscure. `Compile-SourceScript` simply returns the error message from the error stream.

> Perhaps it should be documented that user might need to install compiler dependencies: https://github.com/startersclan/Compile-SourceScript/tree/v2.1.0/test/scripts/dep/linux

Indeed this is an issue with the `amxxpc` compiler which should return a more meaningful error message from missing dependencies. I now recall encountering the same issues with said compiler a number of times over the last couple years.

@leojonathanoh

**Comment by leojonathanoh** [comment]
This should also be documented.

```
# Fails
$ /path/to/my-repo/scripting/amxxpc
compiler failed to instantiate: amxxpc32.so: cannot open shared object file: No such file or directory

# Works
$ cd /path/to/my-repo/scripting
$ ./amxxpc
Welcome to the AMX Mod X 1.8.1-300 Compiler.
Copyright (c) 1997-2013 ITB CompuPhase, AMX Mod X Team

Usage: <file.sma> [options]
Use -? or --help to see full options
```
https://forums.alliedmods.net/showthread.php?p=154320

Whic is why the `-WorkingDirectory` param is important.

**Comment by leojonathanoh** [comment]
By the way https://github.com/startersclan/Compile-SourceScript/tree/v2.1.0/test/scripts/dep/linux is also needed for `amxxpc`, not just for `spcomp` @joeltimothyoh
